########################
# build settings

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: expanded

exclude:
- README.md
- .gitignore
- manuscript


plugins:
- jekyll-remote-theme
- jekyll-avatar


remote_theme: octobook/book-2018-theme
